### ISSUE TITLE
Any chance `FHist.jl` would be helpful?

### ISSUE THREAD

**Issue by Moelf** [Yuan-Ru-Lin/HEPAnalysisUtils.jl#1]
https://moelf.github.io/FHist.jl/dev/notebooks/makie_plotting/

On the "filling" aspect of this histogram, we have event by event push! and also one-shot, the histograms have nice features like 
- `bincounts()`
- `binedges()`
- `binerrors()`
- `nentries()`

to mimic useful features in HEP

**Comment by Yuan-Ru-Lin** [comment]
I'm wondering if it's necessary to abstract histograms from data when doing analysis. As someone who has only studied rare decays and has low statistics to deal with, I only use histograms when I need to visualize results. But that may not be true for other kinds of studies so I am wondering.
